let slideIndex=0,slideTimer;
function showSlide(n){const s=[...document.querySelectorAll('.slide')],d=[...document.querySelectorAll('.dot')];if(!s.length)return;slideIndex=(n+s.length)%s.length;s.forEach((x,i)=>x.classList.toggle('active',i===slideIndex));d.forEach((x,i)=>x.classList.toggle('active',i===slideIndex))}
function resetSlides(){clearInterval(slideTimer);slideTimer=setInterval(()=>showSlide(slideIndex+1),4500)}
function moveSlide(n){showSlide(slideIndex+n);resetSlides()} function goSlide(n){showSlide(n);resetSlides()}
function openCart(){document.querySelector('#cartPanel')?.classList.add('open');document.querySelector('#cartOverlay')?.classList.add('show');renderCart()}
function closeCart(){document.querySelector('#cartPanel')?.classList.remove('open');document.querySelector('#cartOverlay')?.classList.remove('show')}
function total(){return getCart().reduce((s,i)=>{const p=products.find(x=>x.id===i.id);return s+(p?p.price*i.qty:0)},0)}
function renderCart(){const box=document.querySelector('#cartItems'),t=document.querySelector('#cartTotal');if(!box)return;const c=getCart();box.innerHTML=c.length?c.map(i=>{const p=products.find(x=>x.id===i.id);return `<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div class="cart-item-info"><a href="product.html?id=${p.id}"><b>${p.name}</b></a><small>${money(p.price)}</small><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${i.qty}</b><button onclick="changeQty(${p.id},1)">+</button></div></div><button class="remove" onclick="removeProduct(${p.id})">×</button></div>`}).join(''):`<div class="cart-empty">🛒<br><br>السلة فاضية حاليًا.</div>`;if(t)t.textContent=money(total())}
function changeQty(id,d){let c=getCart(),x=c.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<1)c=c.filter(i=>i.id!==id);saveCart(c);renderCart()}
function removeProduct(id){saveCart(getCart().filter(i=>i.id!==id));renderCart()}
function checkoutWhatsApp(){if(!getCart().length)return;let text='مرحبًا، أريد طلب:%0A'+getCart().map(i=>{let p=products.find(x=>x.id===i.id);return encodeURIComponent(p.name+' × '+i.qty)}).join('%0A')+'%0Aالإجمالي: '+encodeURIComponent(money(total()));window.open('https://wa.me/201000000000?text='+text,'_blank')}
document.addEventListener('DOMContentLoaded',()=>{updateCartCount();document.querySelector('#cartOverlay')?.addEventListener('click',closeCart);const s=document.querySelectorAll('.slide');if(s.length){showSlide(0);resetSlides();document.querySelector('.hero-slider')?.addEventListener('mouseenter',()=>clearInterval(slideTimer));document.querySelector('.hero-slider')?.addEventListener('mouseleave',resetSlides)}document.querySelectorAll('.mega-toggle').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();document.querySelector('.mega-menu')?.classList.toggle('open')}));document.addEventListener('click',e=>{if(!e.target.closest('.mega-wrap'))document.querySelector('.mega-menu')?.classList.remove('open')})})
